### ISSUE TITLE
SentencePiece fails?

### ISSUE THREAD

**Issue by gwohlgen** [bheinzerling/bpemb#13]
Hi guys!

I am just trying to test these embeddings, but sentencepiece creates strange byte/unicode characters, which are then obviously not found in the embedding models.

```
me$ pip3 install sentencepiece
Requirement already satisfied: sentencepiece in /home/me/anaconda3/lib/python3.6/site-packages (0.1.2)
```
**Test file:**

```
# -*- coding: utf-8 -*-
  
import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.Load("en.wiki.bpe.op50000.model")
enc = sp.EncodeAsPieces("A test")

for e in enc:
    print(e)
```

b'\xe2\x96\x81'
b'A'
b'\xe2\x96\x81test'

**What am I doing wrong? :)**

**Comment by bheinzerling** [comment]
There are two separate issues here:
1. BPEmb has been trained on lower cased text, so the 4th line should be:

```enc = sp.EncodeAsPieces("a test")```

2. Your environment appears to print bytes instead of strings. b'\xe2\x96\x81' is the bytecode of the character sentencepiece replaces spaces with. If you lowercase your input and decode the bytes into strings with something like `print(e.decode())`, you should get '▁a' and '▁test'.

**Comment by gwohlgen** [comment]
Vielen Dank, that fixed it! :)
